import * as sys from './sys.js';
const i = sys.Map.make(sys.Str.type$, sys.List.make(sys.Str.type$).typeof());
const x = (k, v) => i.set(k, sys.List.make(sys.Str.type$, v));
x("auth.mod", ["ldapMod::LdapMod"]);
x("auth.scheme", ["auth::BasicScheme","auth::Folio2Scheme","auth::HmacScheme","auth::PlaintextScheme","auth::ScramScheme","auth::XPlaintextScheme"]);
x("compiler.bridge.java", ["compilerJava::JavaBridge"]);
x("compiler.dsl.sys::Regex", ["compiler::RegexDslPlugin"]);
x("compiler.dsl.sys::Str", ["compiler::StrDslPlugin"]);
x("conn.tool", ["classicConnExt::ModbusRegMapEditor"]);
x("def.compDefLoader", ["axon::FuncDefLoader","skyarcd::AppDefLoader","skyarcd::ExtDefLoader","skyarcd::FormatDefLoader","skyarcd::SysModDefLoader","skyarcd::TemplateDefLoader","skyarcd::ViewDefLoader"]);
x("fresco.tagField.snmpMibType", ["snmpExt::SnmpMibTypeField"]);
x("hx.cli", ["hx::HelpCli","hx::VersionCli","hxTools::ConvertCli","hxTools::CryptoCli","hxTools::InitCli","hxTools::StubCli","hxd::RunCli"]);
x("hxSedona.scheme", ["hxSedona::DefaultSedonaScheme"]);
x("migrate.RecMigrator", ["migrate::StandardMigrator"]);
x("nav.target", ["navMod::AnyPointNavTarget","navMod::AnyRecNavTarget","navMod::AppNavTarget","navMod::ArcNavTarget","navMod::ConnLearnNavTarget","navMod::ConnNavTarget","navMod::EquipNavTarget","navMod::FavNavTarget","navMod::FileNavTarget","navMod::FuncNavTarget","navMod::IOBinNavTarget","navMod::IODirNavTarget","navMod::IONavTarget","navMod::KpiNavTarget","navMod::MeterNavTarget","navMod::NodeNavTarget","navMod::PointNavTarget","navMod::ProjNavTarget","navMod::RateNavTarget","navMod::RuleNavTarget","navMod::RuleTuningNavTarget","navMod::ScheduleAndCalendarNavTarget","navMod::SiteNavTarget","navMod::SpaceNavTarget","navMod::SparkNavTarget","navMod::SpecNavTarget","navMod::TariffNavTarget","navMod::UserNavTarget","navMod::UserProtoNavTarget","navMod::ViewNavTarget","navMod::WeatherPointNavTarget","navMod::WeatherStationNavTarget"]);
x("ph.lib", ["alphaTestMod","arcbeam","axon","bacnet","betaTestMod","clone","cluster","clusterAuth","conn","connTest","crypto","docker","ecobee","example","haystack","http","hx","hxApi","hxShell","hxTestA","hxTestB","hxUser","io","ldap","math","modbus","mqtt","nest","obix","obs","opc","ph","phIct","phIoT","phScience","platform","platformNetwork","platformSerial","platformTime","point","py","rule4","sedona","snmp","sql","task","testMod","ux","xeto","xml"]);
x("skyarc.ext", ["arcExt::ArcExt","arcKitExt","connExt::ConnExt","demoExt::DemoExt","energyExt::EnergyExt","energyStarExt::EnergyStarExt","eventExt::EventExt","geoExt::GeoExt","greenButtonExt::GreenButtonExt","hisExt::HisExt","hisKitExt::HisKitExt","hvacExt","jobExt::JobExt","mapExt::MapExt","mlExt::MlExt","modbusExt::ModbusExt","notifyExt::NotifyExt","provExt::ProvExt","ruleExt::RuleExt","scheduleExt::ScheduleExt","tariffExt::TariffExt","testConnExt::TestConnExt","testSkyarcd::TestAlphaExt","testSkyarcd::TestBadExt","testSkyarcd::TestBetaExt","testSkyarcd::TestDeltaExt","testSkyarcd::TestGammaExt","weatherExt::WeatherExt"]);
x("skyarc.lib", ["arcExt::ArcLib","connExt::ConnLib","demoExt::DemoLib","energyExt::EnergyLib","energyStarExt::EnergyStarLib","eventExt::EventLib","geoExt::GeoLib","greenButtonExt::GreenButtonLib","hisExt::HisLib","hisKitExt::HisKitLib","jobExt::JobLib","mapExt::MapLib","mlExt::MlLib","modbusExt::ModbusLib","notifyExt::NotifyLib","provExt::ProvLib","ruleExt::RuleLib","scheduleExt::ScheduleLib","tariffExt::TariffLib","weatherExt::WeatherLib"]);
x("skyarc.refScheme", ["skyarcd::HostRefScheme","skyarcd::ProjRefScheme","skyarcd::RecRefScheme","skyarcd::UserRefScheme"]);
x("skyspark.benchmark", ["benchmark::AxonBenchmark","benchmark::CommitBenchmark","benchmark::HisBenchmark"]);
x("sys.uriScheme.dropbox", ["dropbox::DropboxScheme"]);
x("sys.uriScheme.fan", ["sys::FanScheme"]);
x("sys.uriScheme.file", ["sys::FileScheme"]);
x("sys.uriScheme.googledrive", ["googleDrive::GoogleDriveScheme"]);
x("testFolio.impl", ["testSkyarcd::Folio3TestImpl"]);
x("testSys.mult", ["testNative","testSys-1","testSys-2"]);
x("testSys.single", ["works!"]);
x("xeto.bindings", ["hx.control hxControl::XetoBindingLoader","hx.rule4 hxRule","hx.test.xeto testXeto::TestBindingLoader","ion ion::XetoBindingLoader","ion.axon ionAxon","ion.block ionBlock","ion.form ionForm","ion.graphics ionGraphics","ion.inputs ionInputs","ion.map ionMap","ion.play ionPlay","ion.table ionTable","ion.text.code ionTextCode","ion.ux ionUx"]);
sys.Env.cur().__loadIndex(i);
